#!/bin/bash

#start of the line in any bash script should always be a SHEBANG notaion.

#Apart from the first line, none of the lines are considers as a shebang.
#And SHEBANG Notion should always start with #
#SHEBANG : using this notion , we are going to telll sysytem that the interpretor to be used to this script
#Apart from the line 1 or the first line of the  script , anything start with '#' will be refferef a comment
# what is comment ? it is just to add some description or to exclude something